# Generated by Django 5.1.7 on 2025-05-26 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_rename_hight_userprofile_height"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routine_id", models.CharField(max_length=100, unique=True)),
                ("routine_name", models.CharField(max_length=255)),
                ("goal", models.TextField()),
                ("experience_level", models.CharField(max_length=100)),
                ("training_split", models.CharField(max_length=100)),
                ("days_per_week", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("cardio_guidelines", models.TextField(blank=True, null=True)),
                ("flexibility_guidelines", models.TextField(blank=True, null=True)),
                ("precautions", models.TextField(blank=True, null=True)),
                ("coach_response", models.TextField(default="No coach feedback yet.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week_or_number", models.CharField(max_length=255)),
                ("session_focus", models.CharField(max_length=255)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedule",
                        to="gym.trainingroutine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=255)),
                ("target_muscles", models.JSONField(default=list)),
                ("sets", models.CharField(max_length=50)),
                ("reps_or_duration", models.CharField(max_length=100)),
                ("rest_period", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="gym.weeklyscheduleitem",
                    ),
                ),
            ],
        ),
    ]
