# Generated by Django 5.1.7 on 2025-05-26 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_trainingroutine_weeklyscheduleitem_exercise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingroutine",
            name="is_preset",
            field=models.BooleanField(
                default=False, help_text="Is this a system-wide preset routine?"
            ),
        ),
        migrations.AlterField(
            model_name="trainingroutine",
            name="coach_response",
            field=models.TextField(default="No coach feedback."),
        ),
        migrations.AlterField(
            model_name="trainingroutine",
            name="routine_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="trainingroutine",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_routines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
