# Generated by Django 5.1.7 on 2025-06-04 02:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_trainingroutine_is_preset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat_level",
                    models.IntegerField(
                        default=0,
                        help_text="Activity level (0-10 heats) based on recent workout completion.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("last_heat_level_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_routine",
                    models.ForeignKey(
                        blank=True,
                        help_text="The training routine currently selected by the user for this plan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_in_plans",
                        to="gym.trainingroutine",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyWorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="The date this workout was performed or scheduled for.",
                    ),
                ),
                (
                    "routine_log_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the routine used for this day's log.",
                        max_length=255,
                    ),
                ),
                (
                    "logged_exercises",
                    models.JSONField(
                        default=list,
                        help_text="Details of exercises logged for the day, including completion.",
                    ),
                ),
                (
                    "completion_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Overall completion percentage for this day's workout.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "session_notes",
                    models.TextField(
                        blank=True,
                        help_text="Overall notes for this workout session.",
                        null=True,
                    ),
                ),
                (
                    "routine_used",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the actual routine instance used for this log, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_as_daily_workout",
                        to="gym.trainingroutine",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        help_text="The workout plan this log belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="gym.workoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("workout_plan", "date")},
            },
        ),
    ]
