# Generated by Django 5.1.7 on 2025-06-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_workoutplan_dailyworkoutlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="heat_level",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="last_heat_level_update",
        ),
    ]
