# Generated by Django 5.1.7 on 2025-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0006_remove_workoutplan_heat_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyworkoutlog",
            name="logged_exercises",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Details of exercises logged for the day, including completion.",
                null=True,
            ),
        ),
    ]
